stages:
  data_prep:
    cmd: python src/data_prep.py
    deps:
      - src/data_prep.py
      - data/raw/incidents.csv
    outs:
      - data/processed/train.csv
      - data/processed/test.csv

  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/processed/train.csv
    outs:
      - models/risk_model.pkl
